@SmallProductBrowser_HostAddress = https://localhost:7168

GET {{SmallProductBrowser_HostAddress}}/api/products
Accept: application/json

###

GET {{SmallProductBrowser_HostAddress}}/api/products/1
Accept: application/json

###